name: contracts-ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-setup-action@v1
      - name: Fetch main ref for breaking check
        run: git fetch origin main:main
      - name: Lint
        run: buf lint
      - name: Breaking Check
        run: buf breaking --against '.git#branch=main'
      - name: Generate SDKs
        run: buf generate
